[package]
name = "sloggers"
version = "0.1.3"
authors = ["Takeru Ohta <phjgt308@gmail.com>"]
description = "This library provides frequently used slog loggers and convenient functions"
documentation = "https://docs.rs/sloggers"
homepage = "https://github.com/sile/sloggers"
repository = "https://github.com/sile/sloggers"
readme = "README.md"
keywords = ["logger"]
license = "MIT"

[badges]
travis-ci = {repository = "sile/sloggers"}

[dependencies]
log = "0.3"
serde = "1"
serde_derive = "1"
slog = "2"
slog-async = "2"
slog-term = "2"
slog-scope = "3"
slog-stdlog = "2"
trackable = "0.1"

[dev-dependencies]
clap = "2"
tomlconv = "0.1"
